import { readFileSync } from 'node:fs';

import type { CommandModule } from './types.js';

const manifestPaths = [
  new URL('../plugin.manifest.json', import.meta.url),
  new URL('../../dist/plugin.manifest.json', import.meta.url),
] as const;

export const manifestCommand: CommandModule = {
  name: 'manifest',
  options: {},
  requiresContext: false,
  sideEffecting: false,
};

/** The generated bytes are already canonical. Do not parse and stringify them again. */
export function readManifest(): string {
  let lastError: unknown;
  for (const manifestPath of manifestPaths) {
    try {
      return readFileSync(manifestPath, 'utf8');
    } catch (error: unknown) {
      if (!isMissingFile(error)) {
        throw error;
      }
      lastError = error;
    }
  }
  throw lastError;
}

export function writeManifest(stdout: NodeJS.WritableStream): void {
  stdout.write(readManifest());
}

export default manifestCommand;

function isMissingFile(error: unknown): error is NodeJS.ErrnoException {
  return typeof error === 'object' && error !== null && 'code' in error && error.code === 'ENOENT';
}
