import { readFileSync } from 'node:fs';

import type { CommandModule } from './types.js';

const manifestPath = new URL('../plugin.manifest.json', import.meta.url);

export const manifestCommand: CommandModule = {
  name: 'manifest',
  options: {},
  requiresContext: false,
  sideEffecting: false,
};

/** The generated bytes are already canonical. Do not parse and stringify them again. */
export function readManifest(): string {
  return readFileSync(manifestPath, 'utf8');
}

export function writeManifest(stdout: NodeJS.WritableStream): void {
  stdout.write(readManifest());
}

export default manifestCommand;
