export function repositoryPayload(
  overrides: Readonly<Record<string, unknown>> = {},
): Record<string, unknown> {
  return {
    id: 42,
    node_id: 'R_kgDOGithub',
    name: 'example',
    full_name: 'octo/example',
    owner: { login: 'octo', id: 1 },
    private: false,
    visibility: 'public',
    description: null,
    fork: false,
    archived: false,
    disabled: false,
    is_template: false,
    created_at: '2024-01-02T03:04:05Z',
    updated_at: '2024-01-03T03:04:05Z',
    pushed_at: '2024-01-04T03:04:05Z',
    default_branch: 'main',
    homepage: '',
    html_url: 'https://github.com/octo/example',
    clone_url: 'https://github.com/octo/example.git',
    ssh_url: 'git@github.com:octo/example.git',
    topics: ['TypeScript', 'github'],
    license: { spdx_id: 'MIT', key: 'mit' },
    language: 'TypeScript',
    size: 12,
    stargazers_count: 3,
    forks_count: 2,
    watchers_count: 4,
    open_issues_count: 5,
    has_issues: true,
    has_projects: false,
    has_wiki: true,
    has_pages: false,
    has_downloads: true,
    has_discussions: false,
    ...overrides,
  };
}
