import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for this project's documentation.
 * One autogenerated tree over everything under docs/. Page front matter owns
 * the reading order through sidebar_position.
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }]
};

export default sidebars;
